title: Bowen Shi 
description: Research Associate Professor <br> Oden Institute, UT Austin
author: Umberto Villa
author_email: bowenshi@utexas.edu
google_analytics: UA-52448613-2
theme: jekyll-theme-cayman
